### ISSUE TITLE
key generation doesn't work if seed mode is on

### ISSUE THREAD

**Issue by 1989gironimo** [LedgerHQ/openpgp-card-app#29]
I tried to generate a pgp key (selected slot 1, authentication key, RSA 4096) on the ledger nano s with seed mode activated but gpg2 and gpg (on Ubuntu 18.04) fail with "key generation failed: card error" 
If I disable the seed mode, the key generation works flawlessly.

Using firmware 1.4.2 and MCU 1.5.

Do you need more info for debugging this?

**Comment by sg495** [comment]
Somewhat to this point: it took me several attempts before managing to generate the keys with seed mode activated. Sometimes the user pin was asked, sometimes not; sometimes the admin pin was asked, sometimes not. Failures were mostly by `gpg: signing failed: General error`, but a couple of times I also got a `gpg: make_keysig_packet failed: General error`. In all fairness, the same thing happened when the keys finally got generated, so I'm not entirely sure what is going on there.

**Comment by sg495** [comment]
Update: I managed to make it work on Ubuntu 18.04. However, I have yet to confirm that seed mode actually worked: I will need to initialize another device with the same key words to check. I will update this when I have done so.

**Comment by 1989gironimo** [comment]
The key generation works normally if seed mode is off - maybe you've just overlooked to enable it before? Did you test it already?

**Comment by nyanloutre** [comment]
#27 is the same issue

**Comment by 1989gironimo** [comment]
@sg495 Have you tried already the restore of the seed?
Which setting did you use, while generating the pgp key?

**Comment by exp** [comment]
It seems to work correctly for ed25519 keys for me, but not for RSA keys.

This is a little frustrating, as I can't sign certs with ed25519 keys yet.

**Comment by nyanloutre** [comment]
You should try again with latest firmware (1.5)

**Comment by exp** [comment]
@nyanloutre I understand the latest version reduces the slots to 1 (#38)? I don't think I can upgrade in that case because I would lose access to existing keys?

Sorry for the trouble, but I already have 3 generated keys I use for GPG signing. If there will only be one slot in future I will have to rebuild my infrastructure before I can test.

**Comment by 1989gironimo** [comment]
I can confirm, that it's working now!
Generated a mainkey (4096) and subkeys (each 2048) and it worked flawlessly.
But if you change the keysize of the subkeys to 4096 it fails to generate those keys.

**Comment by cslashm** [comment]
@exp There will be 2 version: normal: 1 slot,  and XL: 3 slots

**Comment by cslashm** [comment]
for the 4096, I have still no status, but I think it's PCSC timeout problem.

**Comment by exp** [comment]
@cslashm I updated, and there is only one version. No XL available for the Nano S. I have indeed lost the certificates I feared.

This is a real problem now. Removing features like this without properly informing people? I am supposed to spend another £110 to get access back to keys that I already had?

Please advise.

**Comment by cslashm** [comment]
@exp, you updated from live?
XL incoming. just got little trouble on the deployment chain (which I do not manage)

**Comment by 1989gironimo** [comment]
Tried it with the XL version on firmware version 1.6 and it's working.
