### ISSUE TITLE
Allow for longer PINs

### ISSUE THREAD

**Issue by NiklausHofer** [LedgerHQ/openpgp-card-app#37]
Is there a reason for only allowing 12 digit PINs? Nitrokey allows for 127 digit PINs and unless there is a technical limitation, this app should too.

Also, if I build it myself, can I just increase the variable 'GPG_MAX_PW_LENGTH' in `src/gpg_types.h` or will this break the app in some way?

**Comment by cslashm** [comment]
Design Choice 

You also have to modify UI

Moreover, you will be subject to crypto export restriction law and will not be able to use your own compilation.
