### ISSUE TITLE
Restoring keys on Nano X

### ISSUE THREAD

**Issue by Zizaerion** [LedgerHQ/openpgp-card-app#53]
I'm trying to restore my pgp key setup to the ledger nano x on a Linux mint 19.3 install.  I have the latest udev rules installed, as well as the libccid version 1.4.29-1.  The official release of nano x support hasn't been released yet and it's anticipated that it'll arrive in version 1.4.32.  However, it is possible to manually insert the needed values in the /etc/libccid_Info.plist file which I've done and the gpg --card-status command will show the card and make it usable to generate gpg keypairs.  The only thing I can't seem to do yet is be able to use the pytools restore on it.  I updated the app on device to version 1.4.1.  If I try to run the command for the restore operation (this is from a seeded key generation) it'll always say that 'GPGCard' object has no attribute 'exchange' error.  When I do the card status it says the reader is THRC Smart Card Reader [Nano X] (0001) 00 00.  Any way to go about fixing this or are we just going to have to wait?

**Comment by cslashm** [comment]
the NanoX value to insert in /etc/libccid_Info.plist  is `2c97 / 0004`

It was `2c97/0001` for the NanoS

**Comment by cslashm** [comment]
can you check last github update ? tell me if it is ok or nor

**Comment by Zizaerion** [comment]
Ya I'll check it out.  I would just copy the github repo onto the machine right?  I also assume I would need to use the latest openpgp app as well on the device?

**Comment by Zizaerion** [comment]
It looks like it didn't work, it returned the same error as before.

**Comment by cslashm** [comment]
Please can you provide the command you run, various log, python stacktrace error ....

**Comment by Zizaerion** [comment]
![Screenshot from 2020-04-12 14-18-45](https://user-images.githubusercontent.com/40345044/79078863-9a2a7a80-7cc8-11ea-9e0a-1ab9219a1739.png)

This is the screenshot of the terminal command.

**Comment by Zizaerion** [comment]
I'm going to close this issue as I have been able to resolve it.  I turns out that I didn't put the name for the ledger token in the correct place in the libccid_info_plist file.  Once I changed that, the restore worked without incident.
