### ISSUE TITLE
Does not work with Ledger Nano S Plus

### ISSUE THREAD

**Issue by hashy0917** [LedgerHQ/openpgp-card-app#79]
Hi !

My device is S+.
But I cannot use this app on that device.

(Ubuntu22.04LTS)

```
# gpg --card-status
gpg: selecting openpgp failed: No such device
gpg: OpenPGP card not available: No such device
```

```
# opensc-tool -l
No smart card readers found.
```

What else can I do?

**Comment by jpph** [comment]
have you installed scdaemon and started the service ?

**Comment by hashy0917** [comment]
yes
Of course we are starting

I resolved this issue myself.

Added pid/vid of LedgerNanoS to `/etc/libccid_Info.plist`
After that, when I restarted pcscd, it came to be recognized.
